--오라클 전용 구문
--사번, 사원명, 부서코드 부서명
--DEPT_cod ,DEPT_ID 의 값이 같음 . 
SELECT EMP_ID,EMP_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE,DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--JOB /EMPLOYEE 를 연결해야 직급명 가져올 수 있음
--컬럼명이 같을 때의 처리방법
SELECT EMP_ID,EMP_NAME,JOB_CODE,JOB_NAME
FROM EMPLOYEE,JOB
WHERE JOB_CODE = JOB_CODE;
--방법1. 테이블 명을 명시해준다.
SELECT EMP_ID,EMP_NAME,EMPLOYEE.JOB_CODE,JOB_NAME
FROM EMPLOYEE,JOB
WHERE EMPLOYEE.JOB_CODE = JOB.JOB_CODE;
--방법2. 테이블에 별칭 지정 
SELECT EMP_ID,EMP_NAME,E.JOB_CODE,JOB_NAME
FROM EMPLOYEE E,JOB J
WHERE E.JOB_CODE = J.JOB_CODE;

-- ANSI 표준 구문
--FROM절에 기준 테이블
--조인하고자 하는 테이블 JOIN구문 사용
--컬럼명이 동일하면 USING, 다르다면 ON
SELECT EMP_ID,EMP_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE 
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID );