--춘대학 SELECT(BASIC) 실습문제
--1. 
SELECT DEPARTMENT_NAME "학과 명",CATEGORY 계열
FROM TB_DEPARTMENT;

--2.
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

--3.
--국어국문학과 학과코드 조회
SELECT DEPARTMENT_NO,DEPARTMENT_NAME
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';--001

--국어국문학과 다니는 휴학중인 여학생 찾기 
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' --학과번호
AND ABSENCE_YN='Y' --휴학중 
AND (STUDENT_SSN LIKE '_______2%'  --주민번호를 이용한 성별 체크 
OR STUDENT_SSN LIKE '_______4%');

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY 1 DESC;

--5.
SELECT DEPARTMENT_NAME,CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.
SELECT DISTINCT CATEGORY --중복제거
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

--10.
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' --02학번 (입학년도 기준으로 처리)
AND STUDENT_ADDRESS LIKE '%전주%' --전주 거주자
AND ABSENCE_YN = 'N'; --휴학하지 않은 





